# Generated by Django 4.0.6 on 2023-01-03 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phones', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('slug', models.SlugField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.phonemodel')),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phones.phonestorage')),
            ],
        ),
    ]
