# Generated by Django 4.0.6 on 2023-01-04 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price_table', '0004_rename_model_pricetable_phonemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetable',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pricetable',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
