# Generated by Django 4.0.6 on 2023-01-04 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('price_table', '0002_alter_pricetable_grade'),
        ('listings', '0002_alter_listing_grade'),
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='price',
        ),
        migrations.AddField(
            model_name='phone',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
        migrations.AddField(
            model_name='phone',
            name='price_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='price_table.pricetable'),
        ),
    ]
