# Generated by Django 4.0.6 on 2023-01-04 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phone_price_phone_listing_phone_price_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='status',
            field=models.CharField(choices=[('A', 'Available'), ('S', 'Sold'), ('R', 'Reserved')], default='A', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='phonecolor',
            unique_together={('name', 'phonemodel')},
        ),
        migrations.AlterUniqueTogether(
            name='phonemodel',
            unique_together={('name',)},
        ),
        migrations.AlterUniqueTogether(
            name='phonestorage',
            unique_together={('storage', 'phonemodel')},
        ),
    ]
