# Generated by Django 4.0.6 on 2023-01-04 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_status_alter_phonecolor_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonecolor',
            old_name='name',
            new_name='color',
        ),
        migrations.RenameField(
            model_name='phonemodel',
            old_name='name',
            new_name='model',
        ),
        migrations.AlterUniqueTogether(
            name='phonecolor',
            unique_together={('color', 'phonemodel')},
        ),
        migrations.AlterUniqueTogether(
            name='phonemodel',
            unique_together={('model',)},
        ),
    ]
