# Generated by Django 4.0.6 on 2023-01-04 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_rename_name_phonecolor_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='phonecolor',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='phonemodel',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='phonestorage',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
