# Generated by Django 4.0.6 on 2023-01-04 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0005_alter_phone_slug_alter_phonecolor_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
