# Generated by Django 4.0.6 on 2023-01-04 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_alter_phone_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonestorage',
            name='storage',
            field=models.CharField(choices=[('16GB', '16GB'), ('32GB', '32GB'), ('64GB', '64GB'), ('128GB', '128GB'), ('256GB', '256GB'), ('512GB', '512GB'), ('1024TB', '1024TB')], max_length=100),
        ),
    ]
