# Generated by Django 4.0.6 on 2023-01-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0008_alter_phone_cost_price_alter_phone_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='cost_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
