# Generated by Django 4.0.6 on 2023-01-04 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0009_alter_phone_cost_price'),
        ('listings', '0003_listing_price_table_alter_listing_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='model',
            new_name='phonemodel',
        ),
        migrations.AlterUniqueTogether(
            name='listing',
            unique_together={('phonemodel', 'storage', 'color', 'grade')},
        ),
    ]
